require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JamaatsController do

  # This should return the minimal set of attributes required to create a valid
  # Jamaat. As you add validations to Jamaat, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {
      :jamaat_name => "New Malden",
      :size => "126"
    }
  end
  
  describe "GET 'index'" do
    it "should be successful" do
      get 'index'
      response.should be_success
    end
  end

  describe "GET index" do
    it "assigns all jamaats as @jamaats" do
      jamaat = Jamaat.create! valid_attributes
      get :index
      assigns(:jamaats).should eq([jamaat])
    end
  end

  describe "GET 'show'" do
    it "should be successful" do
      jamaat = Jamaat.create! valid_attributes
      get :show, :id => jamaat.id.to_s
      response.should be_success
    end
  end
  
  describe "GET show" do
    it "assigns the requested jamaat as @jamaat" do
      jamaat = Jamaat.create! valid_attributes
      get :show, :id => jamaat.id.to_s
      assigns(:jamaat).should eq(jamaat)
    end
  end
    
  describe "GET 'new'" do
    it "should be successful" do
      get :new
      response.should be_success
    end
  end
  
  describe "GET new" do
    it "assigns a new jamaat as @jamaat" do
      get :new
      assigns(:jamaat).should be_a_new(Jamaat)
    end
  end

  describe "GET 'edit'" do
    it "should be successful" do
      jamaat = Jamaat.create! valid_attributes
      get :edit, :id => jamaat.id.to_s
      response.should be_success
    end
  end
  describe "GET edit" do
    it "assigns the requested jamaat as @jamaat" do
      jamaat = Jamaat.create! valid_attributes
      get :edit, :id => jamaat.id.to_s
      assigns(:jamaat).should eq(jamaat)
    end
  end
  

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Jamaat" do
        expect {
          post :create, :jamaat => valid_attributes
        }.to change(Jamaat, :count).by(1)
      end

      it "assigns a newly created jamaat as @jamaat" do
        post :create, :jamaat => valid_attributes
        assigns(:jamaat).should be_a(Jamaat)
        assigns(:jamaat).should be_persisted
      end

      it "redirects to the created jamaat" do
        post :create, :jamaat => valid_attributes
        response.should redirect_to(Jamaat.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved jamaat as @jamaat" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jamaat.any_instance.stub(:save).and_return(false)
        post :create, :jamaat => {}
        assigns(:jamaat).should be_a_new(Jamaat)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Jamaat.any_instance.stub(:save).and_return(false)
        post :create, :jamaat => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested jamaat" do
        jamaat = Jamaat.create! valid_attributes
        # Assuming there are no other jamaats in the database, this
        # specifies that the Jamaat created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Jamaat.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => jamaat.id, :jamaat => {'these' => 'params'}
      end

      it "assigns the requested jamaat as @jamaat" do
        jamaat = Jamaat.create! valid_attributes
        put :update, :id => jamaat.id, :jamaat => valid_attributes
        assigns(:jamaat).should eq(jamaat)
      end

      it "redirects to the jamaat" do
        jamaat = Jamaat.create! valid_attributes
        put :update, :id => jamaat.id, :jamaat => valid_attributes
        response.should redirect_to(jamaat)
      end
    end

    describe "with invalid params" do
      it "assigns the jamaat as @jamaat" do
        jamaat = Jamaat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Jamaat.any_instance.stub(:save).and_return(false)
        put :update, :id => jamaat.id.to_s, :jamaat => {}
        assigns(:jamaat).should eq(jamaat)
      end

      it "re-renders the 'edit' template" do
        jamaat = Jamaat.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Jamaat.any_instance.stub(:save).and_return(false)
        put :update, :id => jamaat.id.to_s, :jamaat => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested jamaat" do
      jamaat = Jamaat.create! valid_attributes
      expect {
        delete :destroy, :id => jamaat.id.to_s
      }.to change(Jamaat, :count).by(-1)
    end

    it "redirects to the jamaats list" do
      jamaat = Jamaat.create! valid_attributes
      delete :destroy, :id => jamaat.id.to_s
      response.should redirect_to(jamaats_url)
    end
  end

end
